### ISSUE TITLE
connect to meter

### ISSUE THREAD

**Issue by lxz81** [jantenhove/P1-Meter-ESP8266#1]
Hi,

I just found this arduino/esp-sketch and it is kind of what I'm looking for. Thanks!
But I could not find out how to connect the esp8266 to my smart meter. Can you give me some information or picture about that?

Thanks in advance!

**Comment by jantenhove** [comment]
You need to connect it using an RJ11 connector. This is the pinout to use
![RJ11 P1 connetor](http://gejanssen.com/howto/Slimme-meter-uitlezen/RJ11-pinout.png)

Connect GND->GND on ESP, RTS->3.3V on ESP and RxD->any digital pin on ESP. In my sketch I use D5

**Comment by rubentebogt** [comment]
@jantenhove question about this, what if you have an rj11 connector with 4 kables instead of 6, will it work? And what is the pinout then?
