### ISSUE TITLE
Multiple errors in sketch compile

### ISSUE THREAD

**Issue by onsmam** [jantenhove/P1-Meter-ESP8266#2]
Hi,

Thanx for this great code many thanx.. whem i'm trying to compile it i get this errors:

P1Meter.ino: In function 'bool SendToDomo(int, int, char*)':
P1Meter:107: error: 'HTTP_CODE_OK' was not declared in this scope
P1Meter:114: error: 'class HTTPClient' has no member named 'errorToString'

don't know how to solve this.

thanx in advance

**Comment by onsmam** [comment]
i think the line 107 the variable http_code_ok needs to be declared with some value.. 200?

line 114 is a simple serial print so probably i could just delete the line....

**Comment by jantenhove** [comment]
You need to install the ESP8266 for Arduino as mentioned in the readme. This contains the ESP specific HTTP library.

**Comment by onsmam** [comment]
did it already still same faults, reinstalled still faults..

installed staging version 2.1 rc2 that worked...

**Comment by jantenhove** [comment]
Thanks for the feedback!
